/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\gameboy_tetris_box.glb --types 
Author: Frank Rennau (https://sketchfab.com/rennau)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/gameboy-tetris-box-067a53c4821047888aea55eadbafb3df
Title: GAMEBOY TETRIS BOX
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Shape014_DONKEY_KONG_TETRIS_0: THREE.Mesh
  }
  materials: {
    DONKEY_KONG_TETRIS: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function GameBoy(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/gameboy_tetris_box.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group position={[-66.508, 16.59, 2.961]} rotation={[-Math.PI / 2, 0, Math.PI]}>
        <mesh geometry={nodes.Shape014_DONKEY_KONG_TETRIS_0.geometry} material={materials.DONKEY_KONG_TETRIS} position={[13.62, -50.684, 15.362]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/gameboy_tetris_box.glb')
