/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\replica_of_my_cozy_room.glb --types 
Author: Fahimation (https://sketchfab.com/Popstuff)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/replica-of-my-cozy-room-158c5ae43e0045cebc35929336d1c3ac
Title: Replica of my cozy room
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { type GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Object_3: THREE.Mesh
  }
  materials: {
    palette: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Room(props: React.ComponentProps<'group'>) {
  const { nodes, materials } = useGLTF('/models/replica_of_my_cozy_room.glb') as unknown as GLTFResult
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_3.geometry} material={materials.palette} position={[-46, -46, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/replica_of_my_cozy_room.glb')
